### ISSUE TITLE
Indefinite waiting after failed authentication

### ISSUE THREAD

**Issue by lemmerelassal** [laurentheirendt/devTools#31]
Hi Laurent,

Here's a problem I've encountered:

dev>  Your Github username is: lemmerelassal.  (Success) 
dev>  Your Github email is: lemmer.elassal@me.com.  (Success) 
Username for 'https://github.com': L^Hlemmerelassal
Password for 'https://lemmerelassal@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/lemmerelassal/cobratoolbox.git/'

It doesn't change status.

Regards,
Lemmer

**Comment by laurentheirendt** [comment]
Try running 
```
>> resetDevTools
```
Then, you can try to re-run `contribute`.

**Comment by laurentheirendt** [comment]
May you also try running `contribute(true)` and let me know of the output?

**Comment by laurentheirendt** [comment]
Cannot reproduce - closing for now.
