### ISSUE TITLE
Indefinite wait (another one)

### ISSUE THREAD

**Issue by lemmerelassal** [laurentheirendt/devTools#39]
I did resetDevTools, made new feature, etc.

dev>   -- Configuration -------- 
dev>      GitHub username:       lemmerelassal
dev>      Local directory :      /home/lemmer/work/fork-cobratoolbox
dev>      Remote fork URL:       https://github.com/lemmerelassal/cobratoolbox.git
dev>      Remote repository URL: https://github.com/opencobra/cobratoolbox.git
dev>   -> Your <2094201890> feature (branch) exists locally, but not remotely. Do you want to have your local <2094201890> published? Y/N [Y]:

I pressed enter, now it's stuck.

Operation terminated by user during checkoutBranch (line 172)

In initContribution (line 60)
        checkoutBranch(branchName);

In contribute (line 93)
                        initContribution(strtrim(reply));

**Comment by lemmerelassal** [comment]
It's actually not related to a missing Y. Same thing happens when I reset and do the same, then press Y

**Comment by laurentheirendt** [comment]
Solved.
