### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by lemmerelassal** [laurentheirendt/devTools#43]
-> Please select what you want to do (enter the number): 2
dev>  Your Github username is: lemmerelassal.  (Success) 
dev>  Your Github email is: lemmer.elassal@me.com.  (Success) 
dev>   -> Please define the local path to your fork
       current: /home/lemmer/work/devTools
       Enter the path (press ENTER to use the current path): /home/lemmer/work
Username for 'https://github.com': lemmerelassal
Password for 'https://lemmerelassal@github.com': 
Username for 'https://github.com': lemmerelassal
Password for 'https://lemmerelassal@github.com': 
Username for 'https://github.com': 

etc.

**Comment by laurentheirendt** [comment]
Do you have the latest version? You have to configure your `SSH` key as explained [here](https://github.com/laurentheirendt/devTools/blob/master/PREREQUISITES.md).

**Comment by lemmerelassal** [comment]
Yes and yes (only realized this was a new requirement just now), but it stalls after 

   -> Please select what you want to do (enter the number): 2
dev>  Your Github username is: lemmerelassal.  (Success) 
dev>  Your Github email is: lemmer.elassal@me.com.  (Success) 
dev>   [cloneFork] Cloning the fork https://github.com/lemmerelassal/cobratoolbox.git

**Comment by laurentheirendt** [comment]
It stalls? It must be downloading the repo ...

For debugging, you can also run `contribute(true)`.

**Comment by laurentheirendt** [comment]
Closing in favor of #45
